name: CI

on:
    push:
        branches-ignore:
            - 'github-comments'
    pull_request:
        branches-ignore:
            - 'github-comments'

jobs:
    sphinx-build:
        name: Build (Sphinx)

        runs-on: ubuntu-latest

        container: python:3.7-alpine

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Display Python version"
                run: python -c "import sys; print(sys.version)"

            -   name: "Install Sphinx"
                run: pip install --user sphinx

            -   name: "Install dependencies"
                run: apk add --no-cache git make

            -   name: "Install custom requirements via pip"
                run: pip install -r _build/.requirements.txt

            -   name: "Build documentation"
                run: make -C _build SPHINXOPTS="-nqW -j auto" html

    symfony-docs-builder-build:
        name: Build (symfony/docs-builder)

        runs-on: ubuntu-latest

        continue-on-error: true

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Set-up PHP"
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.2
                    coverage: none
                    tools: "composer:v2"

            -   name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    composer-options: "--prefer-dist"

            -   name: "Build the docs"
                working-directory: _build
                run: php build.php -vvv

    doctor-rst:
        name: Lint (DOCtor-RST)

        runs-on: ubuntu-latest

        steps:
            -   name: "Checkout"
                uses: actions/checkout@v2

            -   name: "Create cache dir"
                run: mkdir .cache

            -   name: "Extract base branch name"
                run: echo "##[set-output name=branch;]$(echo ${GITHUB_BASE_REF:=${GITHUB_REF##*/}})"
                id: extract_base_branch

            -   name: "Cache DOCtor-RST"
                uses: actions/cache@v2
                with:
                    path: .cache
                    key: ${{ runner.os }}-doctor-rst-${{ steps.extract_base_branch.outputs.branch }}

            -   name: "Run DOCtor-RST"
                uses: docker://oskarstark/doctor-rst
                with:
                    args: --short --error-format=github --cache-file=/github/workspace/.cache/doctor-rst.cache
